### PR TITLE
Request to code review

### PR DESCRIPTION
**Pull request by konyan**

### CODE REVIEW

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi @konyan,

### Great job thus far! :raised_hands: However, your `framework.css` is quite scanty. Your page styling looks more like a normal CSS styled page than a framework. Please see the requirements below:

**Grid**
The CSS files define:

- [x]  A class that represents a row

 

- [x] Classes to define columns sized from 1/12th of the row to 100% of the row

- [x]  The defined columns should have breakpoints (example column-large-2)
##### Breakpoints

* [x] The CSS files should define a breakpoint for small screens with a width of up to 720px
* [x] The CSS files should define a breakpoint for medium screens with a width in the range of 720px - 1024px
* [x] The CSS files should define a breakpoint for large screens with width above 1024px
### Box utilities

#### Margins

* [x] The CSS files define separate classes for margin top, bottom, left, right, all margins and auto
* [x] The margins should span from `0 rem` to `1 rem`
* [x] The margins should have breakpoints (e.g. margin-sm-top-1)

#### Padding

* [x] The CSS files define separate classes for padding top, bottom, left, right, all padding and auto
* [x] The padding should span from `0 rem` to `1 rem`
* [x] The padding should have breakpoints (example padding-lg-2)

### Positioning

#### Floats

* [x] The CSS files define separate classes for float left, right and clearing the floats

#### Positions

* [x] The CSS files define separate classes to change the position property of an element to relative, absolute or fixed

### Display

#### Display properties

The CSS files define:

* [x] A class to set the display property of an element to flex
* [x] A class to set the display property to hidden
* [x] A class to set the display property to none
* [x] The none class should have breakpoints (example display-md-none)

#### Flex properties

The CSS files define:

* [x] Classes to set vertical alignment as top, bottom or center
* [x] Classes to set horizontal alignment as left, right or center

### Colors

#### Background and text

The CSS files define:

* [x] At least ten different classes to set the background and text colors of an element

### Text

#### Utilities

The CSS files define:

* [x] Classes to horizontally align text to the left, right or center
* [ ] At least five classes to set the font size of an element
* [x] Three classes to set the font weight of an element (bold, normal, medium)

#### Border

* [x] The CSS files define separate classes for border top, bottom, left, right, all border
* [x] The border should span from 0 to 1rem
* [x] The border should have classes for making box round
* [x] The border should have a class defined to transform a box into a circle

**Kindly submit another code review once these issues have been fixed.** _Happy coding!_ :tada:

**Comment by shshamim63** [comment]
## Status :red_circle: [Required Changes] :red_circle: 
___
Hi @konyan  :wave: ,
Great improvement so far :clap: . Still some space to cover to declare this project as complete.
By seeing the pace you are working I am definitely sure you will cover them at ease. 
___
##### :cyclone: Please follow the instructions below :point_down: to complete this project.
___
### :sparkle: Mandatory Changes :sparkle: 
___
1. I can still see that node_modules file is in this repository. By the way, why do you need it? As far i know it is not needed to add it in this project. Please remove it.
2. Breakpoints: On the [Microverse Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59564673/) it has been clearly mentioned, how you should divide your media breakpoints. and the previous reviewer also mentioned about it. Please fix this issue.
:file_cabinet:  If you have different thought don't forget to share it.
___
#### Please fix the above issues and send another review request. :pray: 
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/)|[Slack](Shakhawat Hossain)

**Comment by konyan** [comment]
I use Breakpoints at my grid  framework with less than 720px and 720px - 1024px and above 1024px for large one.
I don't want to change my Breakpoints at project because my project have 969px medium and  1248 px  for large device.

**Review by suretrust — CHANGES_REQUESTED** [review]
### Kindly fix the breakpoints as required and mentioned on pathwright.

_Happy coding!_

**Review by suretrust — APPROVED** [review]
### Amazing job @konyan, let's get this merged! :+1: 

_Good luck with your future projects and happy coding!_ :tada:

**Pull request merged**
